# Generated by Django 3.2.9 on 2022-05-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20220511_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='categ',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(),
        ),
    ]
